trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - "*"

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Frontend_Tests
  displayName: "Run Frontend Unit Tests"
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'

    - task: Cache@2
      inputs:
        key: 'npm | "$(Agent.OS)" | client/package-lock.json'
        restoreKeys: |
          npm | "$(Agent.OS)"
        path: client/node_modules

    - script: |
        cd client
        npm install
      displayName: "Install Frontend Dependencies"

    - script: |
        npm test -- src/tests --watchAll=false
      workingDirectory: client
      displayName: "Run Frontend Tests from src/tests"